### ISSUE TITLE
Document signals

### ISSUE THREAD

**Issue by mmitucha** [heynemann/motorengine#105]
Hey, 
at first I must say, I really like this project, 
Just wondering if you do not intend to implement Document signals (pre_save, post_save, post_remove, ....). It would be really useful.

**Comment by heynemann** [comment]
I also think it would be very useful. Haven't got to implement it, though.

**Comment by mmitucha** [comment]
Ok, thanks for reply. Maybe I will try to play around and if it is something usefull, I wil get know.
