### ISSUE TITLE
how do sorting by embedded fields?

### ISSUE THREAD

**Issue by Rey8d01** [heynemann/motorengine#81]
Example code

```
class PostMetaDocument(BaseDocument):
    dateCreate = DateTimeField(auto_now_on_insert=True)
    dateUpdate = DateTimeField(auto_now_on_update=True)
    author = StringField()


class PostDocument(BaseDocument):
    __collection__ = "post"

    alias = StringField()
    title = StringField()
    meta = EmbeddedDocumentField(PostMetaDocument)
    text = StringField()
```

I want to get collection PostDocument will be sorted by meta.dateCreate
How I make it via motoengine?

this syntax is not working

```
PostDocument().objects.order_by("meta.dateCreate", direction=-1)
```

because function order_by sort among fields parent document.

**Comment by heynemann** [comment]
I don't think it works that way right now.

Would have to implement it...

**Comment by Rey8d01** [comment]
In documentation have many simple examples and have not complex examples - how works with embeded documents.

May be possible get access to MotorCursor that do query to mongodb? Because document modeling like motorengine is what I need, but I need some manipulation.

**Comment by heynemann** [comment]
Definitely... I'm just VERY low on spare time to work on this. If you want to take a swing at implementing a Pull Request, it would be brilliant.

**Comment by Rey8d01** [comment]
I'm sorry but my knowledge is not enough for development. motorengine looks difficult for me. maybe in the future it will be easier to understand.

**Comment by heynemann** [comment]
Ok, as soon as I get some spare time I'll have a look.
